databases:
  - name: for you
    databaseName: for_you_production
    user: for_you_production_user
    region: singapore

services:
  - type: web
    name: for you
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: for you
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
